### ISSUE TITLE
Two or more instances of color picker in the one example

### ISSUE THREAD

**Issue by dkonopka** [nhn/tui.color-picker#10]
## Version
2.20

## Development Environment
Macintosh, ES6

## Current Behavior
Probably because of `id` in the `<svg>` second (or more) color picker is not working properly (I mean changing background in the details panel).

Demo: 
https://fiddle.jshell.net/grff4Lak/3/

## Expected Behavior
Many instances of color picker should work properly.

**Additional question: there is any option to enable slider panel by default?**

**Comment by kyuwoo-choi** [comment]
@dkonopka thanks for the demo. I confirmed the issue.

**Comment by dkonopka** [comment]
@kyuwoo-choi Is there any estimate of resolving this issue?

**Comment by kyuwoo-choi** [comment]
The fix will be shipped in next patch. But no ETA yet.

**Comment by michgerts** [comment]
Any updates on the fix?

**Comment by Fl0ux** [comment]
I need a fix too. Thanks for your work.

**Comment by michgerts** [comment]
Any updates guys? :)
