### ISSUE TITLE
Example site is 404

### ISSUE THREAD

**Issue by douglasg14b** [nhn/tui.color-picker#17]
https://nhnent.github.io/tui.color-picker/latest/tutorial-example01-basic

**Comment by jung-han** [comment]
@douglasg14b 
Sorry for that. The company name has been changed and the domain has also been changed.
I will fix it as soon as possible. Thanks for issue.

I will give you the correct site address.
https://nhn.github.io/tui.color-picker/latest/tutorial-example01-basic

**Comment by douglasg14b** [comment]
Thanks!
